### ISSUE TITLE
Puzzlerbot fails on Github "ping" request

### ISSUE THREAD

**Issue by skapral** [skapral/puzzlerbot#27]
Attempt to handle Github event with `X-GitHub-Event: ping` header fails with exception:
```
2018-05-27T21:07:51.976679511Z app[web.1]: org.json.JSONException: JSONObject["comments_url"] not found.
2018-05-27T21:07:51.987010830Z app[web.1]: 	at org.json.JSONObject.get(JSONObject.java:520)
2018-05-27T21:07:52.022916382Z app[web.1]: 	at org.json.JSONObject.getString(JSONObject.java:806)
2018-05-27T21:07:52.023087711Z app[web.1]: 	at com.github.skapral.puzzler.github.source.PsrcFromGithubEvent$Inference.lambda$puzzleSource$1(PsrcFromGithubEvent.java:96)
2018-05-27T21:07:52.023119569Z app[web.1]: 	at io.vavr.control.Option.map(Option.java:360)
2018-05-27T21:07:52.023133006Z app[web.1]: 	at com.github.skapral.puzzler.github.source.PsrcFromGithubEvent$Inference.puzzleSource(PsrcFromGithubEvent.java:95)
2018-05-27T21:07:52.023146465Z app[web.1]: 	at com.github.skapral.puzzler.core.source.PsrcInferred.puzzles(PsrcInferred.java:51)
2018-05-27T21:07:52.023158606Z app[web.1]: 	at com.github.skapral.puzzler.core.operation.OpPersistAllPuzzles.execute(OpPersistAllPuzzles.java:54)
2018-05-27T21:07:52.023170310Z app[web.1]: 	at com.github.skapral.puzzler.web.jersey.GithubHookEndpoint.githubHook(GithubHookEndpoint.java:72)
2018-05-27T21:07:52.023183775Z app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-05-27T21:07:52.023195131Z app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-05-27T21:07:52.023205006Z app[web.1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-05-27T21:07:52.023216378Z app[web.1]: 	at java.lang.reflect.Method.invoke(Method.java:498)
2018-05-27T21:07:52.023229012Z app[web.1]: 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
2018-05-27T21:07:52.023306737Z app[web.1]: 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
2018-05-27T21:07:52.023336290Z app[web.1]: 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
2018-05-27T21:07:52.023350737Z app[web.1]: 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
2018-05-27T21:07:52.023362142Z app[web.1]: 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
2018-05-27T21:07:52.023371323Z app[web.1]: 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
2018-05-27T21:07:52.023381335Z app[web.1]: 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
2018-05-27T21:07:52.023391778Z app[web.1]: 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
2018-05-27T21:07:52.023400679Z app[web.1]: 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
2018-05-27T21:07:52.023409177Z app[web.1]: 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
2018-05-27T21:07:52.023419126Z app[web.1]: 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
2018-05-27T21:07:52.023427695Z app[web.1]: 	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
2018-05-27T21:07:52.023436425Z app[web.1]: 	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
2018-05-27T21:07:52.023448191Z app[web.1]: 	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
2018-05-27T21:07:52.023458735Z app[web.1]: 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
2018-05-27T21:07:52.023471201Z app[web.1]: 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
2018-05-27T21:07:52.023480791Z app[web.1]: 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
2018-05-27T21:07:52.023490586Z app[web.1]: 	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
2018-05-27T21:07:52.023500866Z app[web.1]: 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
2018-05-27T21:07:52.023510822Z app[web.1]: 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
2018-05-27T21:07:52.023520946Z app[web.1]: 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
2018-05-27T21:07:52.023529535Z app[web.1]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0pdd** [comment]
@skapral the puzzle [#30](https://github.com/skapral/puzzlerbot/issues/30) is still not solved.
